import {
  AlertCircle,
  Anchor,
  Apple,
  Award,
  Backpack,
  Beer,
  Bell,
  Bike,
  Book,
  BookOpen,
  Briefcase,
  Brush,
  Building,
  Bus,
  Cake,
  Calendar,
  Camera,
  Car,
  Carrot,
  Check,
  CheckCircle,
  Circle,
  Clock,
  Cloud,
  CloudRain,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Crown,
  CupSoda,
  Diamond,
  DollarSign,
  Droplet,
  Droplets,
  Dumbbell,
  Eye,
  EyeOff,
  Feather,
  Film,
  Filter,
  Fish,
  Flag,
  Flame,
  Flower,
  Footprints,
  Frown,
  Gamepad,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  IceCream,
  Image,
  Info,
  Key,
  Landmark,
  Leaf,
  LifeBuoy,
  Link,
  Lock,
  Luggage,
  Map,
  MapPin,
  Martini,
  Medal,
  Meh,
  Mic,
  Moon,
  Mountain,
  Music,
  Navigation,
  Palette,
  Palmtree,
  PenTool,
  Pizza,
  Plane,
  Puzzle,
  Rocket,
  Sailboat,
  Scroll,
  Search,
  Settings,
  Shell,
  Shield,
  Ship,
  ShoppingBag,
  Skull,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  Speaker,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  Target,
  Telescope,
  Tent,
  ThumbsUp,
  Ticket,
  Train,
  Trees,
  TreePine,
  Trophy,
  Umbrella,
  Unlock,
  User,
  UserPlus,
  Users,
  Utensils,
  Video,
  Watch,
  Waves,
  Wind,
  Wine,
  X,
  XCircle,
  Zap,
} from "lucide-react";

export const ICON_LIST = [
  "Mountain", "Tent", "Trees", "TreePine", "Flower", "Leaf", "Palmtree",
  "Sun", "Moon", "Cloud", "CloudRain", "Snowflake", "Wind", "Droplets",
  "Flame", "Waves", "Sunset", "Sunrise", "Umbrella", "Feather",
  "Plane", "Car", "Bike", "Bus", "Train", "Ship", "Anchor", "Sailboat",
  "Map", "MapPin", "Compass", "Globe", "Navigation", "Ticket", "Luggage",
  "Backpack", "Briefcase", "Key", "Landmark", "Building", "LifeBuoy",
  "Camera", "Image", "Video", "Film", "Music", "Mic", "Headphones", "Speaker",
  "Palette", "Brush", "PenTool", "Book", "BookOpen", "Gamepad", "Puzzle",
  "Dumbbell", "Footprints", "Fish", "Binoculars", "Glasses", "Scroll", "Watch",
  "Coffee", "Utensils", "Pizza", "Beer", "Wine", "Martini", "CupSoda",
  "Cake", "Apple", "Carrot", "Soup", "IceCream",
  "Star", "Heart", "Zap", "Trophy", "Award", "Medal", "Crown", "Gem",
  "Diamond", "Shield", "Target", "Flag", "Sparkles", "Rocket", "Ghost",
  "Skull", "ThumbsUp", "Smile", "Meh", "Frown", "Coins", "CreditCard",
  "Check", "CheckCircle", "X", "XCircle", "AlertCircle", "Info", "HelpCircle",
  "User", "Users", "UserPlus", "Lock", "Unlock", "Eye", "EyeOff",
  "Settings", "Filter", "Search", "Tag", "Link", "Home", "Bell", "Calendar",
  "Clock", "Gift", "ShoppingBag", "DollarSign", "Droplet", "Hexagon", "Circle",
  "Shell", "Telescope",
];

const ICON_MAP = {
  AlertCircle,
  Anchor,
  Apple,
  Award,
  Backpack,
  Beer,
  Bell,
  Bike,
  Binoculars: Telescope,
  Book,
  BookOpen,
  Briefcase,
  Brush,
  Building,
  Bus,
  Cake,
  Calendar,
  Camera,
  Car,
  Carrot,
  Check,
  CheckCircle,
  Circle,
  Clock,
  Cloud,
  CloudRain,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Crown,
  CupSoda,
  Diamond,
  DollarSign,
  Droplet,
  Droplets,
  Dumbbell,
  Eye,
  EyeOff,
  Feather,
  Film,
  Filter,
  Fish,
  Flag,
  Flame,
  Flower,
  Footprints,
  Frown,
  Gamepad,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  IceCream,
  Image,
  Info,
  Key,
  Landmark,
  Leaf,
  LifeBuoy,
  Link,
  Lock,
  Luggage,
  Map,
  MapPin,
  Martini,
  Medal,
  Meh,
  Mic,
  Moon,
  Mountain,
  Music,
  Navigation,
  Palette,
  Palmtree,
  PenTool,
  Pizza,
  Plane,
  Puzzle,
  Rocket,
  Sailboat,
  Scroll,
  Search,
  Settings,
  Shell,
  Shield,
  Ship,
  ShoppingBag,
  Skull,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  Speaker,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  Target,
  Telescope,
  Tent,
  ThumbsUp,
  Ticket,
  Train,
  Trees,
  TreePine,
  Trophy,
  Umbrella,
  Unlock,
  User,
  UserPlus,
  Users,
  Utensils,
  Video,
  Watch,
  Waves,
  Wind,
  Wine,
  X,
  XCircle,
  Zap,
};

export const getLucideIcon = (iconName, fallback = Star) => ICON_MAP[iconName] || fallback;

export function RenderLucideIcon({ iconName, size = 20, className, fallback = Star, strokeWidth }) {
  const Icon = getLucideIcon(iconName, fallback);
  return <Icon size={size} className={className} strokeWidth={strokeWidth} />;
}
